package: generated
skip-prune: true
output:
  use-single-file: false
  directory: ..
generate:
  client: true
  client-with-response: true
  models: true
overlay:
  sources:
    - native_uuid_overlay.yaml
user-templates:
  header.tmpl: native_uuid_header.tmpl
